AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for Ferry Availability Checker'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ferry-availability-checker
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  ECRRepositoryURI:
    Description: "ECR Repository URI"
    Value: !GetAtt ECRRepository.RepositoryUri
